# Generated by Django 3.1.7 on 2021-03-18 14:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text='Burayı manuel olarak değiştirmemeniz önerilir.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(help_text='Burayı manuel olarak değiştirmemeniz önerilir.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('slug', models.SlugField(help_text='Burayı manuel olarak değiştirmemeniz önerilir.', unique=True)),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d/', verbose_name='Görsel')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('available', models.BooleanField(default=True, verbose_name='Aktif/Pasif')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
                ('tags', models.ManyToManyField(to='posts.Tag', verbose_name='Etiketler')),
                ('views', models.ManyToManyField(blank=True, related_name='post_views', to='posts.HitCount')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
