# Generated by Django 3.1.7 on 2021-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(blank=True, default='def_user.png', null=True, upload_to='users/', verbose_name='Görsel'),
        ),
    ]
